title: Ryan Raut
position: Instructor (Research Faculty)
affiliation: Washington University in St. Louis
email: raut (at) wustl.edu
google_scholar: https://scholar.google.com/citations?user=fafSHeYAAAAJ&hl=en&oi=ao
google_analytics: G-D2FVNCGJXD
github_link: https://github.com/ryraut
avatar: ./assets/img/default_prof1.png
enable_footnote: false
auto_dark_mode: false
canonical: https://minimal-light.yyliu.net/
