title: Ryan Raut
position: Neuroscience PhD student
affiliation: Washington Univ. in St. Louis
email: raut@wustl.edu
#keywords: minimal academic
google_scholar: https://scholar.google.com/citations?user=fafSHeYAAAAJ&hl=en&oi=ao
github_link: https://github.com/ryraut
avatar: ./assets/img/IMG_20190731_182616_crop.jpg
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
