title: Ryan Raut
position: Shanahan Foundation Fellow
affiliation: Allen Institute for Brain Science & University of Washington, Seattle
email: raut (at) wustl.edu
keywords: systems / theoretical neuroscience
google_scholar: https://scholar.google.com/citations?user=fafSHeYAAAAJ&hl=en&oi=ao
google_analytics: G-D2FVNCGJXD
github_link: https://github.com/ryraut
avatar: ./assets/img/IMG_20190731_182616_crop.jpg
canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
