on: push
jobs:
  build:
    runs-on: ubuntu-latest
    name: script/cibuild
    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1.156.0
      - name: build
        run: script/bootstrap
      - name: test
        run: script/cibuild

            
