on: push
jobs:
  build:
    runs-on: ubuntu-latest
    name: script/cibuild
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
          #bundler-cache: true
      - name: build
        run: script/bootstrap
      - name: test
        run: script/cibuild
